Catkin kobi version

diff --git a/cmake/templates/setup.sh.in b/cmake/templates/setup.sh.in
--- a/cmake/templates/setup.sh.in
+++ b/cmake/templates/setup.sh.in
@@ -5,71 +5,91 @@
 # It tries it's best to undo changes from a previously sourced setup file before.
 # Supported command line options:
 # --extend: skips the undoing of changes from a previously sourced setup file
+#   (in plain sh shell which does't support arguments for sourced scripts you
+#   can set the environment variable `CATKIN_SETUP_UTIL_ARGS=--extend` instead)
 
-SETUP_UTIL="@SETUP_DIR@/_setup_util.py"
+# since this file is sourced either use the provided _CATKIN_SETUP_DIR
+# or fall back to the destination set at configure time
+: ${_CATKIN_SETUP_DIR:=@SETUP_DIR@}
+_SETUP_UTIL="$_CATKIN_SETUP_DIR/_setup_util.py"
+unset _CATKIN_SETUP_DIR
 
-if [ ! -f "$SETUP_UTIL" ]; then
-  echo "Missing Python script: $SETUP_UTIL"
+if [ ! -f "$_SETUP_UTIL" ]; then
+  echo "Missing Python script: $_SETUP_UTIL"
   return 22
 fi
 
 # detect if running on Darwin platform
-UNAME=`which uname`
-UNAME=`$UNAME`
-IS_DARWIN=0
-if [ "$UNAME" = "Darwin" ]; then
-  IS_DARWIN=1
+_UNAME=`uname -s`
+_IS_DARWIN=0
+if [ "$_UNAME" = "Darwin" ]; then
+  _IS_DARWIN=1
 fi
+unset _UNAME
 
 # make sure to export all environment variables
 export CMAKE_PREFIX_PATH
-export CPATH
-if [ $IS_DARWIN -eq 0 ]; then
+if [ $_IS_DARWIN -eq 0 ]; then
   export LD_LIBRARY_PATH
 else
   export DYLD_LIBRARY_PATH
 fi
+unset _IS_DARWIN
 export PATH
 export PKG_CONFIG_PATH
 export PYTHONPATH
-
-# invoke Python script to generate necessary exports of environment variables
-MKTEMP=`which mktemp`
-SETUP_TMP=`$MKTEMP /tmp/setup.sh.XXXXXXXXXX`
-$SETUP_UTIL $@ > $SETUP_TMP
-. $SETUP_TMP
-rm $SETUP_TMP
 
 # remember type of shell if not already set
 if [ -z "$CATKIN_SHELL" ]; then
   CATKIN_SHELL=sh
 fi
 
-# find all environment hooks
-ENV_HOOKS_GENERIC=""
-ENV_HOOKS_SPECIFIC=""
-# order by workspace and ordered inside each workspace
-_IFS=$IFS
-IFS=":"
-FIND=`which find`
-SORT=`which sort`
-for path in $CMAKE_PREFIX_PATH; do
-  # ignore non-catkin workspaces
-  if [ -z "$path" -o ! -f "$path/.catkin" ]; then
-    continue
+# invoke Python script to generate necessary exports of environment variables
+# use TMPDIR if it exists, otherwise fall back to /tmp
+if [ -d "${TMPDIR:-}" ]; then
+  _TMPDIR="${TMPDIR}"
+else
+  _TMPDIR=/tmp
+fi
+_SETUP_TMP=`mktemp "${_TMPDIR}/setup.sh.XXXXXXXXXX"`
+unset _TMPDIR
+if [ $? -ne 0 -o ! -f "$_SETUP_TMP" ]; then
+  echo "Could not create temporary file: $_SETUP_TMP"
+  return 1
+fi
+CATKIN_SHELL=$CATKIN_SHELL "$_SETUP_UTIL" $@ ${CATKIN_SETUP_UTIL_ARGS:-} >> "$_SETUP_TMP"
+_RC=$?
+if [ $_RC -ne 0 ]; then
+  if [ $_RC -eq 2 ]; then
+    echo "Could not write the output of '$_SETUP_UTIL' to temporary file '$_SETUP_TMP': may be the disk if full?"
+  else
+    echo "Failed to run '\"$_SETUP_UTIL\" $@': return code $_RC"
   fi
-  ENV_HOOKS_GENERIC="$($FIND "$path/etc/catkin/profile.d" -maxdepth 1 -name "*.sh" 2>/dev/null | $SORT)
-$ENV_HOOKS_GENERIC"
-  if [ "$CATKIN_SHELL" != "sh" ]; then
-    ENV_HOOKS_SPECIFIC="$($FIND "$path/etc/catkin/profile.d" -maxdepth 1 -name "*.$CATKIN_SHELL" 2>/dev/null | $SORT)
-$ENV_HOOKS_SPECIFIC"
-  fi
-done
-IFS=$_IFS
+  unset _RC
+  unset _SETUP_UTIL
+  rm -f "$_SETUP_TMP"
+  unset _SETUP_TMP
+  return 1
+fi
+unset _RC
+unset _SETUP_UTIL
+. "$_SETUP_TMP"
+rm -f "$_SETUP_TMP"
+unset _SETUP_TMP
 
-# source generic and shell-specific environment hooks
-for envfile in $ENV_HOOKS_GENERIC $ENV_HOOKS_SPECIFIC; do
-  if [ ! -z "$envfile" ]; then
-    . "$envfile"
-  fi
+# source all environment hooks
+_i=0
+while [ $_i -lt $_CATKIN_ENVIRONMENT_HOOKS_COUNT ]; do
+  eval _envfile=\$_CATKIN_ENVIRONMENT_HOOKS_$_i
+  unset _CATKIN_ENVIRONMENT_HOOKS_$_i
+  eval _envfile_workspace=\$_CATKIN_ENVIRONMENT_HOOKS_${_i}_WORKSPACE
+  unset _CATKIN_ENVIRONMENT_HOOKS_${_i}_WORKSPACE
+  # set workspace for environment hook
+  CATKIN_ENV_HOOK_WORKSPACE=$_envfile_workspace
+  . "$_envfile"
+  unset CATKIN_ENV_HOOK_WORKSPACE
+  _i=$((_i + 1))
 done
+unset _i
+
+unset _CATKIN_ENVIRONMENT_HOOKS_COUNT
